### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by summertanh** [makerdao/scd-cdp-portal-chinese#20]
Hello,

when I run yarn start and visit the localhost:3000, I got this error:

![image](https://user-images.githubusercontent.com/16298463/70494272-a9948e00-1b45-11ea-9ac9-f6add8929a71.png)

I am in master branch, please help check.Thanks.

**Comment by michaelelliot** [comment]
Is your issue occurring in this repo (which is `scd-cdp-portal-chinese`) or the `scd-cdp-portal` repo?

**Comment by summertanh** [comment]
@michaelelliot I've found the issue, I should run 'yarn build-css' before 'yarn start' which can build the style.scss to style.css. Thanks.

**Comment by summertanh** [comment]
@michaelelliot Er, I copied the link in README.md, could you please help to change the git link in README.md to this project ?

**Comment by michaelelliot** [comment]
Ah, thanks. Fixed.
